#!/usr/bin/env bash
# =============================================================================
# scripts/rotate-lab-credentials.sh
#
# WHAT THIS IS
#   Rotates the shared lab credentials in every place they live, in one pass:
#
#     fw-01    OPNsense root console password
#     dc-01    MUTASPACE\Administrator (== the local Administrator, because
#              promoting a machine to a domain controller converts the local
#              account into the domain account)
#     .envrc   on this workstation
#     jumpbox  ansible/.secrets/env
#
#   It generates a new password, applies it everywhere, and verifies each
#   endpoint still authenticates afterwards.
#
# WHY IT EXISTS
#   Two reasons, and the second is the one that matters long term.
#
#   1. This lab shipped with a single shared password used by the firewall, the
#      Windows local admin and the domain admin. That value leaked into a
#      committed document and therefore into public git history. A leaked
#      credential in history cannot be deleted - only rotated. This script is
#      that rotation.
#
#   2. Every instructor who stands up their own copy of this lab inherits the
#      SAME placeholder values from .envrc.example. Rotating away from a
#      published default is not a one-off cleanup, it is a step every operator
#      needs, so it belongs in the repository rather than in someone's shell
#      history.
#
# WHAT IT DELIBERATELY DOES NOT DO
#   * It does not print the new password. It writes it to a mode-600 file and
#     tells you where. A password echoed to a terminal ends up in scrollback, in
#     tmux buffers and in screen recordings.
#   * It does not touch the Wazuh credentials. Those are generated by the Wazuh
#     installer and live in ansible/.secrets/wazuh-passwords.txt; rotating them
#     is a different procedure with different failure modes.
#   * It does not rewrite git history. The old value is burned; treat it as
#     public forever and rely on it no longer being valid anywhere.
#
# USAGE
#   ./scripts/rotate-lab-credentials.sh --help
# =============================================================================

set -euo pipefail

readonly SCRIPT_NAME="${0##*/}"
readonly REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Lab endpoints. These are the documented lab-internal addresses, safe to carry
# in the repository - see the secrets policy in CLAUDE.md.
readonly FW_ADDR="10.10.10.1"
readonly JUMPBOX_ADDR="10.10.10.5"
readonly DC_VMID="102"

readonly PVE_HOST="${PVE_SSH_ALIAS:-swc2026}"
readonly LAB_KEY="${MUTASPACE_LAB_SSH_KEY:-$HOME/.ssh/id_ed25519_mutaspace_lab}"

DRY_RUN=0
ASSUME_YES=0
NEW_PASSWORD=""
SKIP_FW=0
SKIP_DC=0
SKIP_JUMPBOX=0

if [[ -t 1 ]]; then
  C_RESET=$'\033[0m'; C_RED=$'\033[31m'; C_GRN=$'\033[32m'
  C_YEL=$'\033[33m'; C_BLU=$'\033[34m'; C_BLD=$'\033[1m'
else
  C_RESET=''; C_RED=''; C_GRN=''; C_YEL=''; C_BLU=''; C_BLD=''
fi

info()    { printf '%s[ .. ]%s %s\n' "$C_BLU" "$C_RESET" "$*"; }
changed() { printf '%s[ ++ ]%s %s\n' "$C_GRN" "$C_RESET" "$*"; }
skipped() { printf '%s[ == ]%s %s\n' "$C_YEL" "$C_RESET" "$*"; }
warn()    { printf '%s[ !! ]%s %s\n' "$C_YEL" "$C_RESET" "$*" >&2; }
die()     { printf '%s[FAIL]%s %s\n' "$C_RED" "$C_RESET" "$*" >&2; exit 1; }

section() { printf '\n%s%s== %s ==%s\n' "$C_BLD" "$C_BLU" "$*" "$C_RESET"; }

usage() {
  cat <<EOF
${SCRIPT_NAME} - rotate the shared MutaSpace SOC Lab credentials

Generates one new password and applies it to fw-01 (OPNsense root), dc-01
(MUTASPACE\\Administrator), this workstation's .envrc, and the jumpbox's
ansible/.secrets/env. Verifies each afterwards.

The new password is written to a mode-600 file and NEVER printed.

USAGE
  ./scripts/${SCRIPT_NAME} [options]

OPTIONS
  --dry-run            Show what would change; touch nothing.
  --yes, -y            Do not prompt for confirmation.
  --password <value>   Use this password instead of generating one.
                       Prefer the generated one; this exists for the case where
                       you must match an external requirement.
  --skip-fw            Do not rotate fw-01.
  --skip-dc            Do not rotate dc-01.
  --skip-jumpbox       Do not update the jumpbox secrets file.
  -h, --help           Show this help.

AFTERWARDS
  The OPNsense config.xml SEED still carries the old hash, so a fw-01 rebuilt
  from the template would come back with the OLD password. Re-export
  PKR_VAR_root_password / PKR_VAR_root_password_hash (this script updates
  .envrc for you) and rebuild template 9004 when convenient:
      task build:opnsense
  Until then the running box and the template disagree, which is safe but worth
  knowing.

EXIT STATUS
  0 on success. Non-zero if any endpoint failed to rotate or failed to verify.
EOF
}

while (( $# )); do
  case "$1" in
    --dry-run)    DRY_RUN=1 ;;
    --yes|-y)     ASSUME_YES=1 ;;
    --password)   shift; [[ $# -gt 0 ]] || die "--password needs a value"; NEW_PASSWORD="$1" ;;
    --password=*) NEW_PASSWORD="${1#*=}" ;;
    --skip-fw)      SKIP_FW=1 ;;
    --skip-dc)      SKIP_DC=1 ;;
    --skip-jumpbox) SKIP_JUMPBOX=1 ;;
    -h|--help)    usage; exit 0 ;;
    *)            usage >&2; die "unknown argument: $1" ;;
  esac
  shift
done

# -----------------------------------------------------------------------------
# Preflight
# -----------------------------------------------------------------------------
section "preflight"

command -v openssl >/dev/null 2>&1 || die "openssl is required (for the crypt hash)"
command -v python3 >/dev/null 2>&1 || die "python3 is required (for password generation)"
[[ -f "$LAB_KEY" ]] || die "lab SSH key not found: ${LAB_KEY}"

ssh -o BatchMode=yes -o ConnectTimeout=8 "$PVE_HOST" true 2>/dev/null \
  || die "cannot reach the Proxmox host via the '${PVE_HOST}' SSH alias"
info "Proxmox host '${PVE_HOST}' reachable"

# -----------------------------------------------------------------------------
# The new secret
#
# Two constraints pull in opposite directions and both are load-bearing.
#
# ALPHABET: alphanumerics only. This value gets typed at an OPNsense installer
# console by a Packer boot_command, handed to net.exe on Windows, and written
# into two shell env files. Restricting the alphabet removes an entire class of
# "works everywhere except one place" quoting bug.
#
# COMPOSITION: Windows default password policy requires 3 of 4 character
# categories (upper, lower, digit, symbol). With symbols excluded by the rule
# above, the only way to reach 3 is upper + lower + digit - so all three must be
# GUARANTEED, not left to chance.
#
# This was found the hard way. The first version sampled 20 characters uniformly
# from letters+digits and happened to draw no digit at all, which is a ~2.6%
# event ((52/62)^20). net.exe rejected it with "The password does not meet the
# password policy requirements", the rotation half-applied, and the cause looked
# like a Windows problem rather than a generator problem. A bug that only fires
# one run in forty is worse than one that always fires.
#
# So: seed one character from each required class, fill the rest uniformly,
# shuffle, and then ASSERT the result before using it.
# -----------------------------------------------------------------------------
section "generate"

if [[ -z "$NEW_PASSWORD" ]]; then
  NEW_PASSWORD="$(python3 -c "
import secrets, string

upper, lower, digits = string.ascii_uppercase, string.ascii_lowercase, string.digits
alphabet = upper + lower + digits

# One from each required category, so coverage is structural rather than lucky.
chars = [secrets.choice(upper), secrets.choice(lower), secrets.choice(digits)]
chars += [secrets.choice(alphabet) for _ in range(19)]

# secrets.SystemRandom().shuffle so position carries no information about class.
secrets.SystemRandom().shuffle(chars)
pw = ''.join(chars)

# Assert rather than trust. If this ever fires, the code above is wrong.
assert len(pw) == 22, len(pw)
assert any(c.isupper() for c in pw) and any(c.islower() for c in pw) and any(c.isdigit() for c in pw)
assert pw.isalnum()
print(pw)")"
  info "generated a new ${#NEW_PASSWORD}-character password (upper+lower+digit guaranteed)"
else
  info "using the operator-supplied password (${#NEW_PASSWORD} characters)"
  [[ "$NEW_PASSWORD" =~ ^[A-Za-z0-9]+$ ]] \
    || warn "the supplied password contains non-alphanumerics; it must survive a csh console, net.exe and two shell files"
fi

# Gate on Windows policy BEFORE touching any endpoint. Rotating fw-01 and then
# discovering Windows will not accept the value is how you end up with half the
# lab on one password and half on another.
if ! python3 -c "
import sys
pw = sys.argv[1]
cats = sum([
    any(c.isupper() for c in pw),
    any(c.islower() for c in pw),
    any(c.isdigit() for c in pw),
    any(not c.isalnum() for c in pw),
])
sys.exit(0 if (len(pw) >= 7 and cats >= 3) else 1)" "$NEW_PASSWORD"; then
  die "password fails Windows default policy (needs >=7 chars and 3 of 4 character categories) - refusing to start a rotation that would half-apply"
fi
info "password satisfies Windows default complexity (3 of 4 categories)"

NEW_HASH="$(openssl passwd -6 "$NEW_PASSWORD")"

# Cross-check the pair before anything is applied. A hash that does not match
# its password is the single worst outcome here: fw-01 rebuilds would come up
# with a password nobody knows.
if ! python3 -c "
import crypt, sys
pw, h = sys.argv[1], sys.argv[2]
sys.exit(0 if crypt.crypt(pw, h) == h else 1)" "$NEW_PASSWORD" "$NEW_HASH" 2>/dev/null; then
  # Python 3.13 removed crypt; fall back to openssl with the extracted salt.
  salt="$(printf '%s' "$NEW_HASH" | cut -d'$' -f3)"
  [[ "$(openssl passwd -6 -salt "$salt" "$NEW_PASSWORD")" == "$NEW_HASH" ]] \
    || die "generated hash does not verify against its password - refusing to continue"
fi
info "password/hash pair cross-checked"

SECRET_DIR="${REPO_ROOT}/.secrets"
SECRET_FILE="${SECRET_DIR}/rotated-credential.txt"

if (( DRY_RUN )); then
  info "[dry] would write the new credential to ${SECRET_FILE}"
else
  mkdir -p "$SECRET_DIR"
  chmod 700 "$SECRET_DIR"
  umask 077
  cat > "$SECRET_FILE" <<EOF
# MutaSpace SOC Lab - rotated shared credential
# Written by ${SCRIPT_NAME} on $(date -Is)
#
# This one value is: fw-01 OPNsense root, and MUTASPACE\\Administrator on dc-01.
# Put it in your password manager and delete this file.
password=${NEW_PASSWORD}
crypt_hash=${NEW_HASH}
EOF
  chmod 600 "$SECRET_FILE"
  changed "wrote the new credential to ${SECRET_FILE} (mode 600, gitignored)"
fi

if (( ! ASSUME_YES && ! DRY_RUN )); then
  printf '\nAbout to rotate fw-01, dc-01, .envrc and the jumpbox secrets.\n'
  read -r -p "Proceed? [y/N] " reply || true
  [[ "$reply" =~ ^[Yy]([Ee][Ss])?$ ]] || die "aborted by operator - nothing was changed"
fi

FAILURES=0

# -----------------------------------------------------------------------------
# fw-01 - OPNsense root
#
# The root shell on OPNsense is csh, so bash constructs have to be piped into
# `sh -c`. `pw usermod root -h 0` reads the new password from stdin, which keeps
# it out of the process table (a plaintext password in `ps` output on a shared
# host is its own small leak).
# -----------------------------------------------------------------------------
section "fw-01 (OPNsense root)"

if (( SKIP_FW )); then
  skipped "fw-01 (--skip-fw)"
elif (( DRY_RUN )); then
  info "[dry] would run: pw usermod root -h 0  on ${FW_ADDR}"
else
  if printf '%s' "$NEW_PASSWORD" | ssh -J "$PVE_HOST" -i "$LAB_KEY" \
      -o StrictHostKeyChecking=no -o BatchMode=yes -o ConnectTimeout=10 \
      "root@${FW_ADDR}" "sh -c 'pw usermod root -h 0'" 2>/dev/null; then
    changed "fw-01 root password rotated"
  else
    warn "fw-01 rotation FAILED"
    FAILURES=$((FAILURES + 1))
  fi
fi

# -----------------------------------------------------------------------------
# dc-01 - MUTASPACE\Administrator
#
# Driven through the QEMU guest agent rather than WinRM, deliberately: WinRM
# authenticates with the very credential being changed, so a mid-rotation WinRM
# session is a race with itself. The guest agent runs as SYSTEM inside the guest
# and does not care.
# -----------------------------------------------------------------------------
section "dc-01 (MUTASPACE\\Administrator)"

if (( SKIP_DC )); then
  skipped "dc-01 (--skip-dc)"
elif (( DRY_RUN )); then
  info "[dry] would run: net.exe user Administrator <new>  in VMID ${DC_VMID}"
else
  # The password reaches the guest as an argv element of qm guest exec. It is
  # visible in the PVE task log for the duration of the call; there is no stdin
  # path through the guest agent. Accepted: the alternative is WinRM, which
  # cannot authenticate reliably while the credential is mid-change.
  if ssh -o BatchMode=yes -o ConnectTimeout=10 "$PVE_HOST" \
      "qm guest exec ${DC_VMID} --timeout 45 -- net.exe user Administrator '${NEW_PASSWORD}'" \
      2>/dev/null | grep -q '"exitcode" : 0'; then
    changed "dc-01 Administrator password rotated"
  else
    warn "dc-01 rotation FAILED - check: ssh ${PVE_HOST} 'qm guest exec ${DC_VMID} -- net.exe user Administrator'"
    FAILURES=$((FAILURES + 1))
  fi
fi

# -----------------------------------------------------------------------------
# .envrc on this workstation
# -----------------------------------------------------------------------------
section ".envrc (workstation)"

ENVRC="${REPO_ROOT}/.envrc"

update_envrc_var() {
  local var="$1" value="$2" file="$3"
  if grep -qE "^export ${var}=" "$file" 2>/dev/null; then
    python3 - "$file" "$var" "$value" <<'PY'
import sys
path, var, value = sys.argv[1], sys.argv[2], sys.argv[3]
out = []
for line in open(path).read().split("\n"):
    if line.startswith(f"export {var}="):
        out.append(f"export {var}='{value}'")
    else:
        out.append(line)
open(path, "w").write("\n".join(out))
PY
    return 0
  fi
  return 1
}

if [[ ! -f "$ENVRC" ]]; then
  warn ".envrc not found at ${ENVRC} - skipping (nothing to update)"
elif (( DRY_RUN )); then
  info "[dry] would update PKR_VAR_root_password, PKR_VAR_root_password_hash, PKR_VAR_windows_admin_password, MUTASPACE_WIN_ADMIN_PASSWORD, MUTASPACE_DOMAIN_ADMIN_PASSWORD in ${ENVRC}"
else
  # The backup goes in .secrets/, NOT beside .envrc.
  #
  # An earlier version wrote ${ENVRC}.bak-<timestamp>. `.envrc` is gitignored but
  # `.envrc.bak-*` is a different filename and was not, so `git add -A` committed
  # three backups containing the OLD PASSWORD IN PLAINTEXT. Caught before push,
  # but the lesson stands: a backup of a secret is still a secret, and it belongs
  # somewhere already known to be ignored rather than somewhere that merely looks
  # adjacent to an ignored path.
  mkdir -p "$SECRET_DIR"
  chmod 700 "$SECRET_DIR"
  cp -a "$ENVRC" "${SECRET_DIR}/envrc.bak-$(date +%Y%m%d%H%M%S)"
  for v in PKR_VAR_root_password PKR_VAR_windows_admin_password \
           MUTASPACE_WIN_ADMIN_PASSWORD MUTASPACE_DOMAIN_ADMIN_PASSWORD; do
    if update_envrc_var "$v" "$NEW_PASSWORD" "$ENVRC"; then
      changed "  ${v}"
    else
      info "  ${v} not present in .envrc - skipped"
    fi
  done
  if update_envrc_var PKR_VAR_root_password_hash "$NEW_HASH" "$ENVRC"; then
    changed "  PKR_VAR_root_password_hash"
  else
    info "  PKR_VAR_root_password_hash not present - skipped"
  fi
  changed ".envrc updated (backup in .secrets/)"
fi

# -----------------------------------------------------------------------------
# jumpbox - ansible/.secrets/env
#
# The jumpbox is the Ansible control node, so its copy of the credential is the
# one the playbooks actually authenticate with. Missing this step is the failure
# where rotation "worked" and every Windows play starts failing an hour later.
# -----------------------------------------------------------------------------
section "jumpbox (ansible/.secrets/env)"

if (( SKIP_JUMPBOX )); then
  skipped "jumpbox (--skip-jumpbox)"
elif (( DRY_RUN )); then
  info "[dry] would update MUTASPACE_WIN_ADMIN_PASSWORD and MUTASPACE_DOMAIN_ADMIN_PASSWORD on ${JUMPBOX_ADDR}"
else
  # The password is base64-encoded for transport and decoded inside the remote
  # python. That is not obfuscation - it is quoting hygiene. The alternative is a
  # password travelling through a local shell, an ssh command string, a remote
  # shell and a heredoc, and every one of those layers has an opinion about
  # quotes. Encoding it means only base64's alphabet ever crosses a boundary.
  pw_b64="$(printf '%s' "$NEW_PASSWORD" | base64 -w0)"

  # The helper is fed on stdin so no password-bearing argv appears in the remote
  # process table.
  remote_script='
import base64, os, sys
path = os.path.expanduser("~/mutaspace-soc-lab/ansible/.secrets/env")
pw = base64.b64decode(sys.argv[1]).decode()
keys = ("MUTASPACE_WIN_ADMIN_PASSWORD", "MUTASPACE_DOMAIN_ADMIN_PASSWORD")
lines, hits = [], 0
for line in open(path).read().split("\n"):
    stripped = line.lstrip()
    replaced = False
    for k in keys:
        if stripped.startswith(f"export {k}=") or stripped.startswith(f"{k}="):
            prefix = "export " if stripped.startswith("export ") else ""
            lines.append(f"{prefix}{k}=\"{pw}\"")
            hits += 1
            replaced = True
            break
    if not replaced:
        lines.append(line)
open(path, "w").write("\n".join(lines))
os.chmod(path, 0o600)
print(f"updated {hits} key(s)")
'
  if ssh -J "$PVE_HOST" -i "$LAB_KEY" \
      -o StrictHostKeyChecking=no -o BatchMode=yes -o ConnectTimeout=10 \
      "labadmin@${JUMPBOX_ADDR}" \
      "cp -a ~/mutaspace-soc-lab/ansible/.secrets/env ~/mutaspace-soc-lab/ansible/.secrets/env.bak && python3 - ${pw_b64}" \
      <<<"$remote_script" 2>/dev/null | grep -q 'updated'; then
    changed "jumpbox secrets updated"
  else
    warn "jumpbox update FAILED - fix by hand: ssh -J ${PVE_HOST} labadmin@${JUMPBOX_ADDR}"
    FAILURES=$((FAILURES + 1))
  fi
fi

# -----------------------------------------------------------------------------
# Verify. Rotation that is not verified is a guess.
# -----------------------------------------------------------------------------
section "verify"

if (( DRY_RUN )); then
  info "[dry] no verification performed"
else
  # fw-01: key-based root SSH must still work (the key is independent of the
  # password, so this proves we did not lock ourselves out of the box).
  if (( ! SKIP_FW )); then
    if ssh -J "$PVE_HOST" -i "$LAB_KEY" -o StrictHostKeyChecking=no \
        -o BatchMode=yes -o ConnectTimeout=10 "root@${FW_ADDR}" true 2>/dev/null; then
      changed "fw-01 root SSH still works"
    else
      warn "fw-01 root SSH BROKEN after rotation"
      FAILURES=$((FAILURES + 1))
    fi
  fi

  # dc-01: ask Windows itself when the password was last set, and check the
  # timestamp actually moved. An absence of errors is not evidence; a changed
  # timestamp is.
  #
  # No pipe and no cmd.exe wrapper on the remote side. An earlier version ran
  #   cmd.exe /c 'net user Administrator | findstr "Password last set"'
  # which reported failure even though the rotation had SUCCEEDED - the pipe and
  # the nested quotes did not survive ssh -> qm guest exec -> cmd.exe. Fetch the
  # whole output and filter it locally, where the quoting rules are known.
  if (( ! SKIP_DC )); then
    dc_pw_set="$(ssh -o BatchMode=yes -o ConnectTimeout=10 "$PVE_HOST" \
        "qm guest exec ${DC_VMID} --timeout 45 -- net.exe user Administrator" 2>/dev/null \
      | python3 -c "
import json, sys
try:
    data = json.load(sys.stdin).get('out-data', '')
except Exception:
    sys.exit(0)
for line in data.replace('\r', '').split('\n'):
    if 'Password last set' in line:
        print(line.split('set', 1)[1].strip())
        break" 2>/dev/null)"

    if [[ -n "$dc_pw_set" ]]; then
      changed "dc-01 password last set: ${dc_pw_set}"
      info "  (confirm this is the current time in the GUEST's clock, not yours)"
    else
      warn "could not read the dc-01 password-last-set timestamp"
      warn "  check by hand: ssh ${PVE_HOST} 'qm guest exec ${DC_VMID} -- net.exe user Administrator'"
      FAILURES=$((FAILURES + 1))
    fi
  fi
fi

# -----------------------------------------------------------------------------
section "summary"

if (( DRY_RUN )); then
  printf '  DRY RUN - nothing was changed.\n\n'
  exit 0
fi

if (( FAILURES )); then
  printf '  %s%d step(s) failed.%s The new credential is in %s.\n\n' \
    "$C_RED" "$FAILURES" "$C_RESET" "$SECRET_FILE"
  printf '  Fix the failures before relying on the rotation: some endpoints now\n'
  printf '  have the new password and some still have the old one.\n\n'
  exit 1
fi

cat <<EOF
  All endpoints rotated and verified.

  NEXT, and do not skip these:

  1. Put the value from ${SECRET_FILE}
     into your password manager, then delete that file.

  2. Reload your shell environment so the new value is in effect:
       direnv reload      # or: set -a; . ./.envrc; set +a

  3. The OPNsense TEMPLATE (9004) still bakes the OLD hash, so a fw-01 rebuilt
     from it would come back with the old password. Rebuild it when convenient:
       task build:opnsense
     The running fw-01 is already correct; this is about future rebuilds.

  4. If any Ansible play authenticates to Windows, re-run it to confirm the new
     credential works end to end:
       task ansible:lab-seed

EOF
